variable_name:
  min_length: # not possible to disable this partial rule, so set it to zero
    warning: 0
    error: 0
disabled_rules:
  - file_length
  - line_length
  - function_body_length
  - todo
  - type_body_length
excluded: 
  - Pods